export default {
  // noAuthenticate
  HOME_SCREEN: 'HOME_SCREEN',
  INDEX_SCREEN: 'INDEX_SCREEN',
  CATEGORY_SCREEN: 'CATEGORY_SCREEN',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  TASK_SCREEN: 'TASK_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  BOTTOM_TAB_BAR: 'BOTTOM_TAB_BAR',
  ADD_SCREEN: 'ADD_SCREEN',

  // authenticate
};
